FROM node:20-alpine

WORKDIR /app/backend

COPY backend/package*.json ./
RUN npm ci

COPY prisma ../prisma
COPY backend ./

RUN npm run prisma:generate && npm run build

CMD ["npm", "run", "worker:prod"]
